In [82]:
from google.colab import drive

drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [83]:
with open('/content/drive/MyDrive/Dataset/Diabetes.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [84]:
print("Size of dataset in characters: ", len(text))

Size of dataset in characters:  67053


In [85]:
print(text[:1000])

The History of Diabetes Mellitus
Robert B. Tattersall
 University of Nottingham, Nottingham, UK
Textbook of Diabetes, 4th edition. Edited by R. Holt, C. Cockram,
A. Flyvbjerg and B. Goldstein. © 2010 Blackwell Publishing.
Keypoints
• Polyuric diseases have been described for over 3500 years. The name
 “ diabetes ” comes from the Greek word for a syphon; the sweet taste
of diabetic urine was recognized at the beginning of the fi rst
millennium, but the adjective “ mellitus ” (honeyed) was only added by
Rollo in the late 18th century.
• The sugar in diabetic urine was identifi ed as glucose by Chevreul in
1815. In the 1840s, Bernard showed that glucose was normally present
in blood, and showed that it was stored in the liver (as glycogen) for
secretion into the bloodstream during fasting.
• In 1889, Minkowski and von Mering reported that pancreatectomy
caused severe diabetes in the dog. In 1893, Laguesse suggested that
the pancreatic “ islets ” described by Langerhans in 1869 produced an

In [86]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [87]:
tokenizer = Tokenizer()

In [88]:
tokenizer.fit_on_texts([text])

In [89]:
tokenizer.word_index

{'the': 1,
 'of': 2,
 'and': 3,
 'in': 4,
 'diabetes': 5,
 'to': 6,
 'a': 7,
 'by': 8,
 'that': 9,
 'was': 10,
 'with': 11,
 'as': 12,
 'insulin': 13,
 '–': 14,
 'for': 15,
 'is': 16,
 'are': 17,
 'from': 18,
 'costs': 19,
 'fi': 20,
 'or': 21,
 '“': 22,
 '”': 23,
 '1': 24,
 'it': 25,
 'were': 26,
 'this': 27,
 'be': 28,
 'health': 29,
 'disease': 30,
 'have': 31,
 'these': 32,
 'but': 33,
 'on': 34,
 'glucose': 35,
 'care': 36,
 'mortality': 37,
 'had': 38,
 'people': 39,
 'complications': 40,
 'an': 41,
 'may': 42,
 'patients': 43,
 's': 44,
 'rst': 45,
 'not': 46,
 'more': 47,
 'such': 48,
 '5': 49,
 'blood': 50,
 'risk': 51,
 'c': 52,
 'only': 53,
 'type': 54,
 '2': 55,
 '’': 56,
 'which': 57,
 'us': 58,
 'because': 59,
 'associated': 60,
 'diabetic': 61,
 'also': 62,
 'cells': 63,
 'been': 64,
 'described': 65,
 'who': 66,
 'they': 67,
 'related': 68,
 'greater': 69,
 'into': 70,
 'developed': 71,
 'all': 72,
 'at': 73,
 'islet': 74,
 'one': 75,
 '4': 76,
 'years': 77,
 'figure': 

In [90]:
len(tokenizer.word_index)

2777

In [91]:
input_sequences = []
for sentence in text.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [92]:
input_sequences

[[1, 286],
 [1, 286, 2],
 [1, 286, 2, 5],
 [1, 286, 2, 5, 349],
 [690, 102],
 [690, 102, 469],
 [691, 2],
 [691, 2, 692],
 [691, 2, 692, 692],
 [691, 2, 692, 692, 470],
 [1193, 2],
 [1193, 2, 5],
 [1193, 2, 5, 693],
 [1193, 2, 5, 693, 694],
 [1193, 2, 5, 693, 694, 695],
 [1193, 2, 5, 693, 694, 695, 8],
 [1193, 2, 5, 693, 694, 695, 8, 350],
 [1193, 2, 5, 693, 694, 695, 8, 350, 696],
 [1193, 2, 5, 693, 694, 695, 8, 350, 696, 52],
 [1193, 2, 5, 693, 694, 695, 8, 350, 696, 52, 697],
 [7, 698],
 [7, 698, 3],
 [7, 698, 3, 102],
 [7, 698, 3, 102, 699],
 [7, 698, 3, 102, 699, 700],
 [7, 698, 3, 102, 699, 700, 471],
 [7, 698, 3, 102, 699, 700, 471, 701],
 [7, 698, 3, 102, 699, 700, 471, 701, 702],
 [87, 703],
 [87, 703, 197],
 [87, 703, 197, 31],
 [87, 703, 197, 31, 64],
 [87, 703, 197, 31, 64, 65],
 [87, 703, 197, 31, 64, 65, 15],
 [87, 703, 197, 31, 64, 65, 15, 160],
 [87, 703, 197, 31, 64, 65, 15, 160, 1195],
 [87, 703, 197, 31, 64, 65, 15, 160, 1195, 77],
 [87, 703, 197, 31, 64, 65, 15, 160

In [93]:
max_len = max([len(x) for x in input_sequences])

In [94]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [95]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,   1, 286],
       [  0,   0,   0, ...,   1, 286,   2],
       [  0,   0,   0, ..., 286,   2,   5],
       ...,
       [  0,   0,   0, ..., 699, 700, 471],
       [  0,   0,   0, ..., 700, 471, 701],
       [  0,   0,   0, ..., 471, 701, 702]], dtype=int32)

In [96]:
X = padded_input_sequences[:,:-1]

In [97]:
y = padded_input_sequences[:,-1]

In [98]:
X.shape

(9591, 34)

In [99]:
X

array([[  0,   0,   0, ...,   0,   0,   1],
       [  0,   0,   0, ...,   0,   1, 286],
       [  0,   0,   0, ...,   1, 286,   2],
       ...,
       [  0,   0,   0, ..., 102, 699, 700],
       [  0,   0,   0, ..., 699, 700, 471],
       [  0,   0,   0, ..., 700, 471, 701]], dtype=int32)

In [100]:
y.shape

(9591,)

In [101]:
y

array([286,   2,   5, ..., 471, 701, 702], dtype=int32)

In [102]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=9592)

In [103]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [104]:
y.shape

(9591, 9592)

### **Using LSTM**

In [105]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [106]:
model = Sequential()
model.add(Embedding(9592, 100, input_length=34))
model.add(LSTM(150))
model.add(Dense(9592, activation='softmax'))

In [107]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [108]:
model.fit(X,y,epochs=200)

Epoch 1/200
300/300 [==============================] - 13s 35ms/step - loss: 7.3694 - accuracy: 0.0461
Epoch 2/200
300/300 [==============================] - 4s 14ms/step - loss: 6.5359 - accuracy: 0.0653
Epoch 3/200
300/300 [==============================] - 3s 10ms/step - loss: 6.3580 - accuracy: 0.0759
Epoch 4/200
300/300 [==============================] - 3s 8ms/step - loss: 6.1982 - accuracy: 0.0831
Epoch 5/200
300/300 [==============================] - 2s 8ms/step - loss: 6.0224 - accuracy: 0.0935
Epoch 6/200
300/300 [==============================] - 3s 11ms/step - loss: 5.8411 - accuracy: 0.1080
Epoch 7/200
300/300 [==============================] - 3s 8ms/step - loss: 5.6438 - accuracy: 0.1203
Epoch 8/200
300/300 [==============================] - 3s 9ms/step - loss: 5.4471 - accuracy: 0.1343
Epoch 9/200
300/300 [==============================] - 3s 8ms/step - loss: 5.2568 - accuracy: 0.1394
Epoch 10/200
300/300 [==============================] - 2s 8ms/step - loss: 5.0672 - a

In [109]:
import numpy as np

In [117]:
import time
text = "β - cell failure"

for i in range(20):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=34, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 [==============================] - 0s 30ms/step
β - cell failure the
1/1 [==============================] - 0s 20ms/step
β - cell failure the same
1/1 [==============================] - 0s 38ms/step
β - cell failure the same with
1/1 [==============================] - 0s 20ms/step
β - cell failure the same with collip
1/1 [==============================] - 0s 20ms/step
β - cell failure the same with collip and
1/1 [==============================] - 0s 20ms/step
β - cell failure the same with collip and the
1/1 [==============================] - 0s 20ms/step
β - cell failure the same with collip and the diagnosis
1/1 [==============================] - 0s 21ms/step
β - cell failure the same with collip and the diagnosis was
1/1 [==============================] - 0s 29ms/step
β - cell failure the same with collip and the diagnosis was superseded
1/1 [==============================] - 0s 20ms/step
β - cell failure the same with collip and the diagnosis was superseded by
1/1 [==========

## **Bidirectional GRU**

In [118]:
from keras.models import Sequential
from keras.layers import Bidirectional, GRU, Dense, Embedding

In [111]:
model = Sequential()

# Add an embedding layer
model.add(Embedding(input_dim=9592, output_dim=100, input_length=34))

# Add first bidirectional GRU layer
model.add(Bidirectional(GRU(units=150, return_sequences=True)))

# Add second bidirectional GRU layer
model.add(Bidirectional(GRU(units=150)))

# Add a dense layer with softmax activation for output
model.add(Dense(9592, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Print model summary
model.summary()


Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 34, 100)           959200    
                                                                 
 bidirectional_2 (Bidirecti  (None, 34, 300)           226800    
 onal)                                                           
                                                                 
 bidirectional_3 (Bidirecti  (None, 300)               406800    
 onal)                                                           
                                                                 
 dense_4 (Dense)             (None, 9592)              2887192   
                                                                 
Total params: 4479992 (17.09 MB)
Trainable params: 4479992 (17.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [114]:
model.fit(X,y,epochs=150)

Epoch 1/150
300/300 [==============================] - 5s 18ms/step - loss: 0.2104 - accuracy: 0.9322
Epoch 2/150
300/300 [==============================] - 4s 14ms/step - loss: 0.1727 - accuracy: 0.9432
Epoch 3/150
300/300 [==============================] - 4s 14ms/step - loss: 0.1599 - accuracy: 0.9462
Epoch 4/150
300/300 [==============================] - 5s 17ms/step - loss: 0.1561 - accuracy: 0.9464
Epoch 5/150
300/300 [==============================] - 7s 24ms/step - loss: 0.1546 - accuracy: 0.9479
Epoch 6/150
300/300 [==============================] - 9s 29ms/step - loss: 0.1547 - accuracy: 0.9466
Epoch 7/150
300/300 [==============================] - 4s 14ms/step - loss: 0.1531 - accuracy: 0.9472
Epoch 8/150
300/300 [==============================] - 4s 14ms/step - loss: 0.1532 - accuracy: 0.9478
Epoch 9/150
300/300 [==============================] - 5s 17ms/step - loss: 0.1550 - accuracy: 0.9457
Epoch 10/150
300/300 [==============================] - 4s 14ms/step - loss: 0.154

In [115]:
import time
text = "Polyuric diseases have been described"

for i in range(15):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=34, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 [==============================] - 0s 20ms/step
Polyuric diseases have been described for
1/1 [==============================] - 0s 20ms/step
Polyuric diseases have been described for over
1/1 [==============================] - 0s 21ms/step
Polyuric diseases have been described for over 3500
1/1 [==============================] - 0s 20ms/step
Polyuric diseases have been described for over 3500 years
1/1 [==============================] - 0s 30ms/step
Polyuric diseases have been described for over 3500 years the
1/1 [==============================] - 0s 21ms/step
Polyuric diseases have been described for over 3500 years the name
1/1 [==============================] - 0s 19ms/step
Polyuric diseases have been described for over 3500 years the name patients
1/1 [==============================] - 0s 20ms/step
Polyuric diseases have been described for over 3500 years the name patients with
1/1 [==============================] - 0s 21ms/step
Polyuric diseases have been described for over 